version: '3.6'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '${HOSTNAME}'
    environment:
      GITLAB_ROOT_PASSWORD: '${ROOT_PASSWORD}'
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = ${SSH_PORT}
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_HOST}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_HOST}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = ${SMTP_STARTTLS}
        gitlab_rails['smtp_tls'] = ${SMTP_TLS}
        gitlab_rails['smtp_openssl_verify_mode'] = "none"
        gitlab_rails['gitlab_email_from'] = "${SMTP_USERNAME}"
        gitlab_rails['gitlab_email_reply_to'] = "noreply@${HOSTNAME}"
    ports:
      - '80:80'
      - '443:443'
      - '${SSH_PORT}:${SSH_PORT}'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data: